### Create customer

POST http://localhost:8000/customers
Content-Type: application/x-www-form-urlencoded

first_name=Elisabeth&
last_name=Windsor&
birth_date=1926-04-21&
user_name=qelisabeth&
password=thequeen